### ISSUE TITLE
Firefox with firebug requirement

### ISSUE THREAD

**Issue by ellipsoid** [clojurebridge-minneapolis/track1-chatter#20]
We list Firefox with Firebug as a requirement on https://github.com/clojurebridge-minneapolis/track1-chatter/blob/master/Pages/Page%201_Intro%20TOC.md. We should probably edit the instructions to use the different browsers' default inspector tools.

**Comment by tmarble** [comment]
Closed by https://github.com/clojurebridge-minneapolis/installfest/commit/a5c5a318f879db241301332cbbeeb4f41cc752c9
