### ISSUE TITLE
Overview contains reference to LightTable

### ISSUE THREAD

**Issue by MageMasher** [clojurebridge-minneapolis/track1-chatter#29]
http://clojurebridge-minneapolis.github.io/track1/Page_1_Intro_TOC.html#overview

The overview contains a reference to LightTable. We should capture this change when we change the editor.

**Comment by tmarble** [comment]
Closed by https://github.com/clojurebridge-minneapolis/installfest/commit/a5c5a318f879db241301332cbbeeb4f41cc752c9
