### ISSUE TITLE
Quick Copy change #4

### ISSUE THREAD

**Issue by MageMasher** [clojurebridge-minneapolis/track1-chatter#33]
Leiningen version discrepancy between required tools and prerequisites.

http://clojurebridge-minneapolis.github.io/track1/Page_1_Intro_TOC.html#prerequisites

`You will need Leiningen 2.0.0 or above installed.` is it 2.0.0 or `Leiningen 2.5+` like the Required tools says?

**Comment by tmarble** [comment]
Non-issue: if you install lein today you get 2.7.1. (requirements removed as part of #32)
