### ISSUE TITLE
Copy changd #26

### ISSUE THREAD

**Issue by MageMasher** [clojurebridge-minneapolis/track1-chatter#55]
http://clojurebridge-minneapolis.github.io/track1/Page_5_More_code_changes.html#adding-hiccup

At the bottom of adding hiccup there is an asterisk next to the word function. What is the purpose? I see no other reference. Is it to instigate a question? 

````
The hiccup function(*) page/html5 generates an HTML page. It expects Clojure vectors with symbols representing corresponding HTML tags. Hiccup will automatically add the closing tag when it reaches the end of the vector.

<<< include screenshot >>>
````

Also we should probably actually include the screenshot rather than just a placeholder.

**Comment by tmarble** [comment]
Closed by https://github.com/clojurebridge-minneapolis/installfest/commit/a5c5a318f879db241301332cbbeeb4f41cc752c9
